#!/bin/sh /etc/rc.common

START=80
NAME=aliddns

NE_TIPS='AliDDNS NOT ENABLED'

restart() {
	start
}

uci_get_by_name() {
	local ret=$(uci get $NAME.$1.$2 2>/dev/null)
	echo ${ret:=$3}
}

uci_bool_by_name() {
	case "$(uci_get_by_name $1 $2)" in
		1|on|true|yes|enabled) return 0;;
	esac
	return 1
}

start() {
	$(uci_bool_by_name base enable) || {
		stop
		return 0
	}
	sed -i "/${NE_TIPS}/d" /var/log/aliddns.log

	time=$(uci_get_by_name base time 10)
	[ 0 -lt $time -a $time -lt 60 ] || time=10

	[ -f /etc/crontabs/root ] || mkdir -p /etc/crontabs && touch /etc/crontabs/root
	sed -i '/aliddns/d' /etc/crontabs/root
	echo "*/$time * * * * /usr/sbin/aliddns >> /var/log/aliddns.log 2>&1" >> /etc/crontabs/root
	/etc/init.d/cron restart

	( /usr/sbin/aliddns >> /var/log/aliddns.log 2>&1 ) &
}

stop() {
	sed -i '/aliddns/d' /etc/crontabs/root >/dev/null 2>&1
	/etc/init.d/cron restart
	echo "${NE_TIPS}" > /var/log/aliddns.log
}
